// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsLiveScoreboard.Data;

namespace SportsLiveScoreboard.Data.Migrations
{
    [DbContext(typeof(SportsDbContext))]
    [Migration("20180827190931_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SportsLiveScoreboard.Data.Models.Competitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompetitorFromMatchId");

                    b.Property<bool>("IsComputedPerson");

                    b.Property<bool>("IsTheWinnerOfMatch");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("RoomId");

                    b.HasKey("Id");

                    b.HasIndex("CompetitorFromMatchId");

                    b.HasIndex("RoomId");

                    b.ToTable("Competitors");
                });

            modelBuilder.Entity("SportsLiveScoreboard.Data.Models.Event", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .HasMaxLength(20);

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("OwnerId");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("SportsLiveScoreboard.Data.Models.Game.GameRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EventId")
                        .IsRequired();

                    b.Property<int>("GameSettingsId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("SportTypeId");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("GameSettingsId");

                    b.HasIndex("SportTypeId");

                    b.ToTable("GameRooms");
                });

            modelBuilder.Entity("SportsLiveScoreboard.Data.Models.Game.GameScoreInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PointsId");

                    b.HasKey("Id");

                    b.HasIndex("PointsId");

                    b.ToTable("GameScoreInfo");
                });

            modelBuilder.Entity("SportsLiveScoreboard.Data.Models.Game.GameSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsGamePlayable");

                    b.Property<bool>("IsPeriodPlayable");

                    b.Property<bool>("IsPlayedForTime");

                    b.Property<bool>("IsSetPlayable");

                    b.Property<int>("MinGamesCount");

                    b.Property<int>("MinPeriodNumber");

                    b.Property<int>("MinScore");

                    b.Property<int>("MinSetsCount");

                    b.HasKey("Id");

                    b.ToTable("GameSettings");
                });

            modelBuilder.Entity("SportsLiveScoreboard.Data.Models.Game.Match", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ActualStartTime");

                    b.Property<int>("Competitor1Id");

                    b.Property<int>("Competitor2Id");

                    b.Property<int>("GameSettingsId");

                    b.Property<int>("RoomId");

                    b.Property<DateTime>("ScheduledStartTime");

                    b.Property<int>("ScoreInfoId");

                    b.Property<int>("Status");

                    b.Property<int>("TypeId");

                    b.Property<int>("WinnerIndex");

                    b.HasKey("Id");

                    b.HasIndex("Competitor1Id");

                    b.HasIndex("Competitor2Id");

                    b.HasIndex("GameSettingsId");

                    b.HasIndex("RoomId");

                    b.HasIndex("ScoreInfoId");

                    b.HasIndex("TypeId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("SportsLiveScoreboard.Data.Models.Game.Score", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Competitor1");

                    b.Property<int>("Competitor2");

                    b.Property<int?>("GameScoreInfoId");

                    b.Property<int?>("GameScoreInfoId1");

                    b.Property<int>("SequentialNumber");

                    b.HasKey("Id");

                    b.HasIndex("GameScoreInfoId");

                    b.HasIndex("GameScoreInfoId1");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("SportsLiveScoreboard.Data.Models.Game.SportType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("SportTypes");
                });

            modelBuilder.Entity("SportsLiveScoreboard.Data.Models.Identity.Role", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("SportsLiveScoreboard.Data.Models.Identity.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("SportsLiveScoreboard.Data.Models.UserEvents", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("EventId");

                    b.HasKey("UserId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("UserEvents");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("SportsLiveScoreboard.Data.Models.Identity.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SportsLiveScoreboard.Data.Models.Identity.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SportsLiveScoreboard.Data.Models.Identity.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("SportsLiveScoreboard.Data.Models.Identity.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SportsLiveScoreboard.Data.Models.Identity.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SportsLiveScoreboard.Data.Models.Identity.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SportsLiveScoreboard.Data.Models.Competitor", b =>
                {
                    b.HasOne("SportsLiveScoreboard.Data.Models.Game.Match", "CompetitorFromMatch")
                        .WithMany()
                        .HasForeignKey("CompetitorFromMatchId");

                    b.HasOne("SportsLiveScoreboard.Data.Models.Game.GameRoom", "Room")
                        .WithMany("Competitors")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SportsLiveScoreboard.Data.Models.Event", b =>
                {
                    b.HasOne("SportsLiveScoreboard.Data.Models.Identity.User", "Owner")
                        .WithMany("Events")
                        .HasForeignKey("OwnerId");
                });

            modelBuilder.Entity("SportsLiveScoreboard.Data.Models.Game.GameRoom", b =>
                {
                    b.HasOne("SportsLiveScoreboard.Data.Models.Event", "Event")
                        .WithMany("Rooms")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SportsLiveScoreboard.Data.Models.Game.GameSettings", "GameSettings")
                        .WithMany()
                        .HasForeignKey("GameSettingsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SportsLiveScoreboard.Data.Models.Game.SportType", "SportType")
                        .WithMany()
                        .HasForeignKey("SportTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SportsLiveScoreboard.Data.Models.Game.GameScoreInfo", b =>
                {
                    b.HasOne("SportsLiveScoreboard.Data.Models.Game.Score", "Points")
                        .WithMany()
                        .HasForeignKey("PointsId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SportsLiveScoreboard.Data.Models.Game.Match", b =>
                {
                    b.HasOne("SportsLiveScoreboard.Data.Models.Competitor", "Competitor1")
                        .WithMany("MatchesAsCompetitor1")
                        .HasForeignKey("Competitor1Id");

                    b.HasOne("SportsLiveScoreboard.Data.Models.Competitor", "Competitor2")
                        .WithMany("MatchesAsCompetitor2")
                        .HasForeignKey("Competitor2Id");

                    b.HasOne("SportsLiveScoreboard.Data.Models.Game.GameSettings", "Settings")
                        .WithMany()
                        .HasForeignKey("GameSettingsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SportsLiveScoreboard.Data.Models.Game.GameRoom", "Room")
                        .WithMany("Matches")
                        .HasForeignKey("RoomId");

                    b.HasOne("SportsLiveScoreboard.Data.Models.Game.GameScoreInfo", "ScoreInfo")
                        .WithMany()
                        .HasForeignKey("ScoreInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SportsLiveScoreboard.Data.Models.Game.SportType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SportsLiveScoreboard.Data.Models.Game.Score", b =>
                {
                    b.HasOne("SportsLiveScoreboard.Data.Models.Game.GameScoreInfo")
                        .WithMany("Games")
                        .HasForeignKey("GameScoreInfoId");

                    b.HasOne("SportsLiveScoreboard.Data.Models.Game.GameScoreInfo")
                        .WithMany("Sets")
                        .HasForeignKey("GameScoreInfoId1");
                });

            modelBuilder.Entity("SportsLiveScoreboard.Data.Models.UserEvents", b =>
                {
                    b.HasOne("SportsLiveScoreboard.Data.Models.Event", "Event")
                        .WithMany("Moderators")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SportsLiveScoreboard.Data.Models.Identity.User", "User")
                        .WithMany("EventsInModeration")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
